### ISSUE TITLE
批量标签功能无法使用

### ISSUE THREAD

**Issue by kotoriww** [uparrows/LANraragi_cn#12]
![image](https://user-images.githubusercontent.com/33814719/211549257-ba822d16-7a17-4b9b-af76-74121e10ebb8.png)
运行就会卡主 看log日志 好像是标签服务无法使用
![image](https://user-images.githubusercontent.com/33814719/211549346-77f170ab-f071-4877-96b0-07970f7eb8ea.png)

**Comment by uparrows** [comment]
用的哪个插件？

**Comment by kotoriww** [comment]
没有用插件吧, 默认的选项栏 
![image](https://user-images.githubusercontent.com/33814719/211965357-4f055ee4-9aa8-4dca-9ae3-833ee632a4d1.png)

**Comment by kotoriww** [comment]
![image](https://user-images.githubusercontent.com/33814719/212060652-e507dc35-a3b8-44e5-895a-b458dc1504fe.png)
成功了一个 乱码了
