### ISSUE TITLE
数据库1000个标签后  lanraragi_cn无法启动

### ISSUE THREAD

**Issue by kotoriww** [uparrows/LANraragi_cn#13]
上传了1200本漫画  1000个标签 230G左右的占用
docker启动 在900标签的时候 3-4分钟会启动成功 现在到第五分钟服务会启动失败
日志:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-lrr-setup: executing... 
[cont-init.d] 01-lrr-setup: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
mkdir: can't create directory '/root/lanraragi/log': File exists
mkdir: can't create directory '/root/lanraragi/public/temp': File exists
rm: can't remove '/root/lanraragi/public/temp/server.pid': No such file or directory
rm: can't remove '/root/lanraragi/public/temp/shinobu.pid': No such file or directory
rm: can't remove '/root/lanraragi/public/temp/minion.pid': No such file or directory
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening

后测试英文原版 挂载至第六分钟 服务正常启动
日志:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
rm: can't remove '/home/koyomi/lanraragi/public/temp/server.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid-s6': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid-s6': No such file or directory
s6-rc: info: service init successfully started
s6-rc: info: service redis: starting
s6-rc: info: service redis successfully started
s6-rc: info: service lanraragi: starting
s6-rc: info: service lanraragi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Attempting to create directory /home/koyomi/perl5
[2023-01-15 13:29:02.31906] [20731] [info] Listening at "http://*:3000"
[2023-01-15 13:29:02.31946] [20731] [info] Manager 20731 started
[2023-01-15 13:29:02.32321] [20770] [info] Worker 20770 started
[2023-01-15 13:29:02.32536] [20776] [info] Worker 20776 started
[2023-01-15 13:29:02.32692] [20782] [info] Worker 20782 started
[2023-01-15 13:29:02.32798] [20731] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
[2023-01-15 13:29:02.32874] [20788] [info] Worker 20788 started
Use of uninitialized value $userdir in concatenation (.) or string at ./lib/Shinobu.pm line 66.
invalid top directory at /usr/share/perl5/core_perl/File/Find.pm line 130.
Use of uninitialized value in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Config.pm line 130.
Use of uninitialized value in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Config.pm line 130.
Starting LANraragi with UID/GID : 9001/9001
usermod: no changes
Server PID will be at /home/koyomi/lanraragi/public/temp/server.pid
ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
Enabling AOF on Redis... This might take a while.

这是我的数据库文件
链接：https://pan.baidu.com/s/1R50LviYGlPQekQUH1qpsCA?pwd=u37g 
提取码：u37g 
大佬可以帮忙看下是什么原因导致的么

**Comment by kotoriww** [comment]
登陆密码为:123456(虽然服务都起不来)

**Comment by WindyCloudCute** [comment]
我目前好像没碰到这个问题可以复现一下这个问题么我帮你修修看

**Comment by kotoriww** [comment]
我试了一下 发现 widnows docker 才会出现这问题  我用nas启动反而没问题 widnows docker wsl2 数量超标统计都会蹦 nas里稳的EB

**Comment by kotoriww** [comment]
而且nas 启动 基本20几秒就成功了 widnows docker 启动最短也要5分钟

**Comment by WindyCloudCute** [comment]
可以吧标签复制出来一下吗  我这边那个windows的docker试试 刚好开发环境我没删掉

**Comment by kotoriww** [comment]
> 可以吧标签复制出来一下吗 我这边那个windows的docker试试 刚好开发环境我没删掉

光有标签好像没用 得有存档才行 存档太大了 光标签我这里也能正常启动

**Comment by kotoriww** [comment]
不太好确定啥原因  话说老哥你能把最新版打个dokcer么

**Comment by WindyCloudCute** [comment]
我下班打一个给你

**Comment by WindyCloudCute** [comment]
我这边打算用golang重写LANraragi解决原版出现的性能问题
😅😅就是不知道什么时候做好

**Comment by kotoriww** [comment]
没事 等你

**Comment by WindyCloudCute** [comment]
这个是我刚打出来的镜像你导入到docker里试试看吧[点击下载](http://ct.windycloud.cn:4/get.tar)

**Comment by kotoriww** [comment]
好的 感谢

**Comment by kotoriww** [comment]
@WindyMadman  老哥 你镜像是不是打的不对啊 导入img之后 运行是portainer.io 啊

**Comment by kotoriww** [comment]
portainer/portainer-ce:latest

**Comment by WindyCloudCute** [comment]
不好意思我上传错了 你重新用这个链接下载一次

**Comment by kotoriww** [comment]
咦 没看见链接啊

**Comment by kotoriww** [comment]
好了好了

**Comment by WindyCloudCute** [comment]
如果方便的话你可以来qq群499167780找我   我不经常看Github
