### ISSUE TITLE
和并请求

### ISSUE THREAD

**Issue by WindyCloudCute** [uparrows/LANraragi_cn#15]
大佬我给你开了个合并, 孩子没新版本用要洗掉了啦!快合并一下吧 ε=ε=ε=┏(゜ロ゜;)┛

**Comment by uparrows** [comment]
好的，谢谢啦，今天晚上下班回来就弄

WindyMadman ***@***.***> 于 2023年1月26日周四 00:44写道：

**Comment by WindyCloudCute** [comment]
哈哈，好的，我这次是吧能修好的全给修好了 
你这边构建docker直接build就行 有什么需要添加的就得自己改改配置文件了
我这边docker生产环境已经测试过了没什么问题

还有就是我在页面加了一个我的署名 如果不同意可以您这边可以自行推送删掉

**Comment by uparrows** [comment]
😂改动的内容比较多，手机屏幕小实在不好看，宿舍又没给配电脑，等我加完最后三天班就回家弄，先本地编译个使用着吧，如果可以另外开个仓库接手汉化就更好啦🙏，因为我无法保证有足够的时间弄了，疫情那会堆了太多的活还有人辞职😂，太难了

WindyMadman ***@***.***> 于 2023年1月26日周四 16:33写道：

**Comment by WindyCloudCute** [comment]
没事的大佬您可以先忙您的。
或者您同意的话我这边另开一个仓库fork也可以,然后我这边内容引用你原来写的内容(可能会有修改),然后您个人这边等以后有空了想接管我这边再给您做分支合并。
主要是我这边其实也跟您差不多,没啥空闲时间,所以当时提交就做的是分支合并请求。
😂😂而且我这边对perl那是一窍不通,只能从头学然后按照经验一点点搞。
