### ISSUE TITLE
请问大佬有没有兴趣做一个tag翻译的插件啊

### ISSUE THREAD

**Issue by atlanticfirst** [uparrows/LANraragi_cn#2]
现在的tag全是英文,看起来很违和来着,隔壁有人已经把翻译都做好了https://github.com/EhTagTranslation/Database,请问大佬有没有兴趣做个tag替换,把英文tag批量替换成中文的插件?

**Comment by uparrows** [comment]
lan里面的tag是实时从网站获取，EhTagBuilder是从数据库网页，获得翻译数据替换当前网页，原理不一样，直接从e站获取的tag都是英文，之前尝试过把标签搞成中文，不过会造成标签重复，而且因为编码的原因还会乱码，所以就放弃了。
![1](https://user-images.githubusercontent.com/38988286/135438830-e31aee54-9152-4af6-8e84-553547c3f8bb.png)
![2](https://user-images.githubusercontent.com/38988286/135439712-bd08f0e1-b160-4fbf-8aff-98d68cf53b0e.JPG)

**Comment by uparrows** [comment]
如果不嫌烦的话，可以在 数据库备份/恢复 里面导出数据库为json，然后以文本方式打开替换关键词，以后会尝试有没有办法解决
