### ISSUE TITLE
请教下怎么爬标签，目前做了几个步骤了。不知道少了那些。

### ISSUE THREAD

**Issue by lifenots** [uparrows/LANraragi_cn#3]
![Snipaste_2021-12-01_19-26-12](https://user-images.githubusercontent.com/14367662/144226856-2f1ed668-6cfc-479f-b612-6a7b4075be50.png)

![Snipaste_2021-12-01_19-27-07](https://user-images.githubusercontent.com/14367662/144226666-8c273635-a1be-4dc0-a483-55d78748ab3a.png)
)
爬标签就只按了这两步，不行，报错，群晖确定通过软路由从美国出去了。
报错是这样的：
开始批量获取标签操作...
************
处理 ID 5b06afdc880f7efbbfb200e89ba346747d63d209 (No matching EH Gallery Found!)时发生插件错误

休眠 4 秒.
处理 ID 91e2b5badf1b5d51dd02d952beeaa31f61750ff4 (No matching EH Gallery Found!)时发生插件错误

休眠 4 秒.
Cancelling...
************
(code 1005)

**Comment by uparrows** [comment]
操作没有问题，翻译下来就是 找不到匹配的图库，就是没有在e站搜索到这个文件，建议使用fakku这个插件，能够匹配到更多的文件

**Comment by lifenots** [comment]
> 操作没有问题，翻译下来就是 找不到匹配的图库，就是没有在e站搜索到这个文件，建议使用fakku这个插件，能够匹配到更多的文件

是代理的问题，我把整个群晖用美国代理出去就可以爬了，但是gwf模式不行，在直通域名下面我添加了下面的域名也不行，整个群晖翻出去会影响DNS和下载，请教下路由怎么走适合？
exhentai.org
alt.hentaiverse.org
e-hentai.org
g.e-hentai.org
lofi.e-hentai.org
r.e-hentai.org
api.e-hentai.org
ehgt.org
gt0.ehgt.org
ehtracker.org
1.ehtracker.org
a.ehtracker.org
ehwiki.org
forums.e-hentai.org
hentaiathome.net
rpc.hentaiathome.net
hentaiverse.org
repo.e-hentai.org
ul.e-hentai.org
xml.ehgt.org
upld.e-hentai.org

**Comment by uparrows** [comment]
我用的openwrt，直接添加强制域名就可以，其他的设备不清楚
![1](https://user-images.githubusercontent.com/38988286/144231673-9e06e40d-b1f9-44ac-adac-5e457a166cc4.JPG)
