### ISSUE TITLE
docker上最新镜像还是老版本

### ISSUE THREAD

**Issue by Viacesace** [uparrows/LANraragi_cn#4]
docker上的lastest镜像实际还是0.8.3，但是tags里能看到最新的0.8.4，求更新

**Comment by uparrows** [comment]
![屏幕截图 2022-02-17 105616](https://user-images.githubusercontent.com/38988286/154396065-6ada718d-83f4-48f1-87b6-f36a6cfe8184.png)
测试下docker上已有0.8.4的镜像，docker镜像是workflow自动编译，不会遗漏，你可以换下docker的源或者拉取镜像时带上版本号。
