### ISSUE TITLE
关于元数据插件E-Hentai和登陆插件E-Hentai的问题

### ISSUE THREAD

**Issue by sakura-umi** [uparrows/LANraragi_cn#5]
您好！
非常感谢您的汉化！
最近在使用中，我发现元数据插件E-Hentai有使用exhentai刮削数据的选项，如下图
![image](https://user-images.githubusercontent.com/56287117/164975907-de8ea851-02a9-4d57-9cfd-5f656fe3d1ee.png)
但是，在登陆插件里，并没有让填入进入exhentai站的关键cookie `igneous`. 由于exhentai里站的政策，这导致了大部分地区（非欧美原生ip）无法直接连接到exhentai（在浏览器中登录成功一次后再次登录可以选择任意ip也是因为浏览器把`igneous`的cookie缓存了下来），而最终导致刮削失败。但如果带有`igneous` cookie进行访问，则可以无视此限制，使用任意ip访问。
想请问下，是否可以魔改该插件，以支持带`igneous` cookie访问exhentai呢？非常感谢！

**Comment by uparrows** [comment]
平时用该插件都是路由器上配置强制走代理的域名，所以没关心这个，后续空了研究下

**Comment by Atomseek** [comment]
> 

大佬，我平时都是用ehvewer看了顺手下载。
我观察了一下画廊的链接，大概是这样的格式：https://exhentai.org/g/aaaa/bbbb
其中，aaaa对应了ehvewer中画廊的Gid，bbbb对应了画廊的Token。
我发现下载的文件里面有个.ehviewer，里面的第三第四行记录了这两个参数，只要这两个参数拼凑一下就能还原链接，就无须使用标题搜索了。我看了一下原作者的插件源码，大概知道怎么改程序了，但是我不懂perl语言如何打开压缩包并且读取里面的文件，没法获取文件中这两个参数，所以请教一下大大，怎么读取压缩包内.ehviewer文件里这两个参数？

.ehviewer前四行样式：
VERSION2
00000018
aaaa
bbbb


另外，我可以尝试一下魔改插件，完成上面那位老哥的要求。

**Comment by Atomseek** [comment]
> 您好！ 非常感谢您的汉化！ 最近在使用中，我发现元数据插件E-Hentai有使用exhentai刮削数据的选项，如下图 ![image](https://user-images.githubusercontent.com/56287117/164975907-de8ea851-02a9-4d57-9cfd-5f656fe3d1ee.png) 但是，在登陆插件里，并没有让填入进入exhentai站的关键cookie `igneous`. 由于exhentai里站的政策，这导致了大部分地区（非欧美原生ip）无法直接连接到exhentai（在浏览器中登录成功一次后再次登录可以选择任意ip也是因为浏览器把`igneous`的cookie缓存了下来），而最终导致刮削失败。但如果带有`igneous` cookie进行访问，则可以无视此限制，使用任意ip访问。 想请问下，是否可以魔改该插件，以支持带`igneous` cookie访问exhentai呢？非常感谢！

这位老哥，我修改了一下登录脚本，把原本填star cookie的选项改为了填igneous cookie，完成了你想要的功能，你把压缩包解压，然后在插件配置那里点击上传插件，选择解压出来的EHentai.pm。完成上传后，重启一下lanraragi容器即可。

我只是简单修改了一下脚本第94和103行，把提交cookie的名字从star改为igneous而已。
[EHentai.zip](https://github.com/uparrows/LANraragi_cn/files/10095739/EHentai.zip)

**Comment by uparrows** [comment]
> > 您好！ 非常感谢您的汉化！ 最近在使用中，我发现元数据插件E-Hentai有使用exhentai刮削数据的选项，如下图 ![image](https://user-images.githubusercontent.com/56287117/164975907-de8ea851-02a9-4d57-9cfd-5f656fe3d1ee.png) 但是，在登陆插件里，并没有让填入进入exhentai站的关键cookie `igneous`. 由于exhentai里站的政策，这导致了大部分地区（非欧美原生ip）无法直接连接到exhentai（在浏览器中登录成功一次后再次登录可以选择任意ip也是因为浏览器把`igneous`的cookie缓存了下来），而最终导致刮削失败。但如果带有`igneous` cookie进行访问，则可以无视此限制，使用任意ip访问。 想请问下，是否可以魔改该插件，以支持带`igneous` cookie访问exhentai呢？非常感谢！
> 
> 这位老哥，我修改了一下登录脚本，把原本填star cookie的选项改为了填igneous cookie，完成了你想要的功能，你把压缩包[EHentai.zip](https://github.com/uparrows/LANraragi_cn/files/10095739/EHentai.zip)解压，然后在插件配置那里点击上传插件，选择解压出来的EHentai.pm。完成上传后，重启一下lanraragi容器即可。
> 
> ![Screenshot_20221126_134958](https://user-images.githubusercontent.com/67729048/204074379-047eba95-033a-406d-805a-a8705246677a.png)
> 
> 我只是简单修改了一下脚本第94和103行，把提交cookie的名字从star改为igneous而已。

谢谢，最近由于疫情原因已经远离我的pc一段时间了，等后续能够回家会继续跟进，感谢你为解决该问题的付出

**Comment by Atomseek** [comment]
我根据其他插件修修改改实现了我想要的功能了，不用麻烦大佬了。

**Comment by Atomseek** [comment]
插件我放这了，您可以考虑pr过去
[Ehviewer.zip](https://github.com/uparrows/LANraragi_cn/files/10095998/Ehviewer.zip)

**Comment by uparrows** [comment]
> 插件我放这了，您可以考虑pr过去 [Ehviewer.zip](https://github.com/uparrows/LANraragi_cn/files/10095998/Ehviewer.zip)

好的，等过几天解封就弄😁
