### ISSUE TITLE
代理无法使用

### ISSUE THREAD

**Issue by xiaobaozi233** [uparrows/LANraragi_cn#7]
![image](https://user-images.githubusercontent.com/68990805/185345194-1bf4eb78-9122-4d90-9113-d5768c4632c3.png)

版本 0.8.6添加了代理参数发现插件并没有走代理通道，麻烦帮忙看看。

**Comment by uparrows** [comment]
你的那个代理的地址是不是输错了?，192.168.1.3:7890

**Comment by xiaobaozi233** [comment]
截图时候填错了，但填过好几次，改过来对的情况下也Connect timeout.

**Comment by uparrows** [comment]
> 截图时候填错了，但填过好几次，改过来对的情况下也Connect timeout.

测试了多次，http_proxy都是正常的，容器也能ping通，能够正常刮削，没有复现bug，确实没办法了，可以向原开发者提issue看看能不能解决

**Comment by uparrows** [comment]
> 截图时候填错了，但填过好几次，改过来对的情况下也Connect timeout.
已更新源码，正在编译，后续重新拉取下镜像试一试

**Comment by xiaobaozi233** [comment]
还是不行。。。我也挂路由器的代理算了
