### ISSUE TITLE
修复非欧美地区登录的Ehentai登录插件

### ISSUE THREAD

**Issue by Atomseek** [uparrows/LANraragi_cn#8]
releases的说明搞错了，修复的非欧美地区登录的插件应该是这个：lib/LANraragi/Plugin/Login/EHentai.pm
我又稍微修改了一下，直接把我修改的文件替换上去没问题的。
[EHentai.zip](https://github.com/uparrows/LANraragi_cn/files/10183917/EHentai.zip)

而之前上传的Ehviewer插件，是从手机的e站阅读软件Ehviewer下载的文件中，提取画廊链接。然后调用原作者的e站加标签插件，绕过搜索标题，直接访问源画廊链接获取标签。
这两个是不一样的呢....

另外能不能把我相关的信息隐藏一下啊，怕被熟人看到不太好（逃）

**Comment by Atomseek** [comment]
e站5号时候更新了，可以只用Gid搜索画廊了，Ehviewer下载的文件标题就有Gid，并且已经原作者也更新了e站插件，支持从文件名中提取Gid直接搜索了，我整的Ehviewer插件可能作用不大了，就不用放上去了。

**Comment by Atomseek** [comment]
我已经向原作者PR了新的登录插件，您直接同步上游应该就可以了

**Comment by uparrows** [comment]
> 我已经向原作者PR了新的登录插件，您直接同步上游应该就可以了

ok，我修改下
